name: Automatic Pull Request Labeling
run-name: 'Set labels - PR #${{ github.event.pull_request.number }} ("${{ github.event.pull_request.title }}")'
#
# Set labels for pull requests automatically based on size (modified via job 'label-size') and file categories (modified via .github/labeler)
#

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - name: Add default label
        uses: tella-adam/add-labels@v1
        with:
          labels: |
            Ready to merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
